version: '3.9'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      global_network:
        aliases:
          - redis_bd_global
  mongo:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo-data:/data/db
    ports:
      - "1888:27017"
    networks:
      global_network:
        aliases:
          - mongo_bd_global
  api:
    image: "sergiopa2000/api-calculator"
    ports:
      - "443:443"
      - "3000:3000"
    networks:
      global_network:
        aliases:
          - api_global
    depends_on:
      - mongo

networks:
  global_network:
    name: global_net
    driver: bridge
    ipam:
      driver: default

volumes:
  mongo-data: